services:
  app:
    depends_on:
      - 'postgres'
    build: .
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '256mb'
    ports:
      - '3000:3000'
    volumes:
      - '.:/application'
      - '/application/tmp/cache'
    environment:
      - POSTGRES_HOST=postgres

  postgres:
    image: "postgres:16"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512mb'
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data

volumes:
  postgres:
