services:
  app:
    depends_on:
      - 'postgres1'
      - 'postgres2'
      - 'postgres3'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/application'
      - '/application/tmp'
    environment:
      - POSTGRES_HOST_1=postgres1
      - POSTGRES_HOST_2=postgres2
      - POSTGRES_HOST_3=postgres3
      - REDIS_URL=redis://redis:6379/0
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  sidekiq:
    depends_on:
      - 'postgres1'
      - 'postgres2'
      - 'postgres3'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/application'
      - '/application/tmp'
    environment:
      - POSTGRES_HOST_1=postgres1
      - POSTGRES_HOST_2=postgres2
      - POSTGRES_HOST_3=postgres3
      - REDIS_URL=redis://redis:6379/0
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  postgres1:
    image: "postgres:16"
    container_name: postgres1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./tmp/postgres_1_data:/var/lib/postgresql/data
      - ./docker-configs/postgres1/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./docker-configs/postgres1/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  postgres2:
    image: "postgres:16"
    depends_on:
      - 'postgres1'
    container_name: postgres2
    restart: always
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./tmp/postgres_2_data:/var/lib/postgresql/data
      - ./docker-configs/postgres2/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./docker-configs/postgres2/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  postgres3:
    image: "postgres:16"
    depends_on:
      - 'postgres1'
    container_name: postgres3
    restart: always
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./tmp/postgres_3_data:/var/lib/postgresql/data
      - ./docker-configs/postgres3/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./docker-configs/postgres3/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  redis:
    image: "redis:latest"
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

volumes:
  postgres1:
  postgres2:
  postgres3:
  redis:
