default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") { "postgres" } %>

development:
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST_1") { "localhost" } %>
  database: highload_architect_development
  servers:
    replica1:
      <<: *default
      host: postgres2
      database: highload_architect_development
    replica2:
      <<: *default
      host: postgres2
      database: highload_architect_development

test:
  <<: *default
  database: highload_architect_test

staging: *default

production:
  <<: *default
  database: "social_network"
  username: "application"
  password: <%= ENV["POSTGRES_PASSWORD"] %>
